app:
  runner:
    plan-runner-execute-interval-ms: 60000
    allocator-execute-interval-ms: 3000
    proxy-execute-time-interval-ms: 60000
    concurrency-queue-execute-time-interval-ms: 300000
    concurrency-queue-expired-time-interval-ms: 600000
    max-overflow-interval-ms: 86400000
    expired-cleaner-execute-interval-ms: 3600000
    max-expired-interval-ms: 2592000000
    proxy-get-configs:
      -
        className: xin.manong.darwin.runner.proxy.zdaye.ZdayeProxyGetter
        baseURL: http://www.zdopen.com
        appId: 202602091351125438
        appSecret: 8ddc5cb8645c1806
        username: 202602091351125438
        password: 58142744
        batchSize: 5