weapon:
  common:
    redis:
      client:
        mode: SINGLE
        connection-pool-size: 200
        password: ${weapon/redis/password}
        address: r-bp1zhcujlmuqz1sr6j.redis.rds.aliyuncs.com:6379
        db: 0